// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cloud_logic_custom": [
        {
            "name": "amplifyapi",
            "endpoint": "https://kih5kcs1t2.execute-api.ap-southeast-2.amazonaws.com/test",
            "region": "ap-southeast-2"
        }
    ],
    "aws_content_delivery_bucket": "myapp-20191204174828-hostingbucket-test",
    "aws_content_delivery_bucket_region": "ap-southeast-2",
    "aws_content_delivery_url": "http://myapp-20191204174828-hostingbucket-test.s3-website-ap-southeast-2.amazonaws.com"
};


export default awsmobile;
